# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('fitterKakao', '0002_auto_20170901_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaBottom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cri_bot_length', models.FloatField(default=0)),
                ('cri_waist', models.FloatField(default=0)),
                ('cri_hip', models.FloatField(default=0)),
                ('cri_crotch', models.FloatField(default=0)),
                ('cri_thigh', models.FloatField(default=0)),
                ('cri_hem', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CriteriaTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cri_top_length', models.FloatField(default=0)),
                ('cri_shoulder', models.FloatField(default=0)),
                ('cri_chest', models.FloatField(default=0)),
                ('cri_sleeve', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='sameclothes',
            name='same_photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[300, 300], upload_to='%Y/%m/%d'),
        ),
    ]
